version: '3.8'
services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/gradle/project
      # Cache Gradle dependencies
      - gradle-cache:/home/gradle/.gradle
    command: gradle :load-test-core:clean :load-test-core:build :load-test-core:test --info

volumes:
  gradle-cache:
